### ISSUE TITLE
BUG: flaky (or broken) CI

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt_astro_analysis#146]
I just fixed a couple issues with CI in #145 
However Python 3.9 and 3.10 jobs are flaky (or consistently failing) with new errors:
```
#!/bin/bash -eo pipefail
if [ ! -f $YT_DATA/enzo_tiny_cosmology/DD0046/DD0046 ]; then
    source $BASH_ENV
    source $HOME/venv/bin/activate
    mkdir -p $YT_DATA
    girder-cli --api-url https://girder.hub.yt/api/v1 download 577c09480d7c6b0001ad5be2 $YT_DATA/enzo_tiny_cosmology
fi


Too long with no output (exceeded 10m0s): context deadline exceeded
```
Fixing this goes beyond my current expertise

**Comment by brittonsmith** [comment]
Thanks for taking it this far! I'll check this out when I have the chance.

**Comment by neutrinoceros** [comment]
looks like we forgot to close, but I think the situation was resolved.
