### ISSUE TITLE
TST: CI breaks (missing `girder-cli`)

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt_astro_analysis#182]
CI is currently failing with
```
/bin/bash: line 5: girder-cli: command not found
```

I don't know what changed since the last successful run from 9 days ago (https://app.circleci.com/pipelines/github/yt-project/yt_astro_analysis/588/workflows/4aa0390e-b355-4995-82aa-a27dabc93a57)
I will look it up

**Comment by neutrinoceros** [comment]
It seems plausible that something changed in CircleCI.
I think `grider-client` is the actual command we want to invoke, and somehow it was okay to abbreviate it previously but not anymore ? I'll try this simple patch before digging any further

**Comment by Xarthisius** [comment]
`pip install girder-client` ? It provides both `girder-cli` and `girder-client`

**Comment by neutrinoceros** [comment]
this is already done through
```shell
python -m pip install -r test_requirements.txt
```

**Comment by Xarthisius** [comment]
It's in `install-dependencies` command and I don't see it being used in any workflow.

**Comment by Xarthisius** [comment]
and before `girder-client` was in setup.cfg, which was removed in https://github.com/yt-project/yt_astro_analysis/pull/175

**Comment by neutrinoceros** [comment]
> It's in install-dependencies command and I don't see it being used in any workflow.

I see, good catch ! I guess it didn't break immediately because the program survived for some time through caching ?
Anyway, it should be an easy fix then, thank you !
