### ISSUE TITLE
Issue Running Rockstar with Generic Particle Data

### ISSUE THREAD

**Issue by Ecskrabacz10** [yt-project/yt_astro_analysis#199]
I am currently trying to figure out how to get a new simulation file type to work with Rockstar and am having a bit of trouble. I've started to try and use a generic particle data set, which will have the particles' position, velocity, and mass. When I try to run rockstar through the astro_analysis tool, I run into a UnitParseError saying that "Mpccm" is not an available unit symbol.

To combat this, I tried creating a cosmology through yt.utilities.cosmology as I could define an Mpccm that way, but I am still running into the same issue.

This is the current code that I am trying to run.
```
import numpy as np
import yt
yt.enable_parallelism()
from mpi4py import MPI
import h5py
from yt.extensions.astro_analysis.halo_analysis import HaloCatalog
import yt.units as u
from yt.utilities.cosmology import Cosmology

# Loading the file --------------------------------------------------------
filename = "concept/output/standtest/snapshot_a=0.10.hdf5"
f = h5py.File(filename,"r")

# Direct data from HDF5 File ----------------------------------------------
p = f["/components/total matter/pos"][:]          #Units = Mpc
mom = f["/components/total matter/mom"][:]          #Units = 10^10 Msun * Mpc/Gyr 
L = f.attrs["boxsize"]                              #Units = Mpc
N = f["/components/total matter"].attrs["N"]
M = f["/components/total matter"].attrs["mass"]     #Units = 10^10 Msun
v = mom/M                                         #Units = Mpc/Gyr

# Cosmology / adapting for Mpccm/h -----------------------------------------
H0 = f.attrs["H0"]/u.Gyr
H0 = round(H0.to("km/s/Mpc"))
ocdm = f.attrs["Ωcdm"]
ob = f.attrs["Ωb"]
om = ob + ocdm

co = Cosmology(hubble_constant = H0.value/100, omega_matter = om, omega_lambda = 1 - om)
pos = co.arr(p, f.attrs["unit length"])
vel = co.arr(v, f.attrs["unit length"] + "/" + f.attrs["unit time"])
mass = co.arr(np.full(N,M), f.attrs["unit mass"])

# Putting data into yt -----------------------------------------------------
data = {}
data["particle_position_x"] = pos[:,0]
data["particle_position_y"] = pos[:,1]
data["particle_position_z"] = pos[:,2]
data["mass"] = mass
data["particle_velocity_x"] = vel[:,0]
data["particle_velocity_y"] = vel[:,1]
data["particle_velocity_z"] = vel[:,2]
bbox = np.array([[0,L],[0,L],[0,L]])

ds = yt.load_particles(data, length_unit = 1e6 * u.parsec, mass_unit = 1e10 * u.Msun, time_unit = 1e9 * u.yr, bbox = bbox)

# Finding halos -------------------------------------------------------------
hc = HaloCatalog(data_ds = ds, finder_method = "rockstar", finder_kwargs={"num_readers": 1, "num_writers": 1})
hc.create()
```

This code produces the following error.
[error.txt](https://github.com/yt-project/yt_astro_analysis/files/11692410/error.txt)

Would anybody be able to help me out with this problem?

**Comment by brittonsmith** [comment]
As well, I would not use use the unit_registry associated with the Cosmology object. In there, the comoving and proper frames are incorrectly set equal to each other, which is an unfortunate limitation of the unit system.

**Comment by Ecskrabacz10** [comment]
Thank you so much! I just fixed up a little bit of the code and took your suggestion and I was able to run the code. I also added some other things to my dataset (current redshift, omega matter, etc.) so that rockstar would run with the correct parameters.

**Comment by Ecskrabacz10** [comment]
It seems like a=0.10 was too early, I just tested the code on a = 0.30 and it is loading perfectly! Thank you so much for the help!
