### ISSUE TITLE
Halo catalog weirdness under python3

### ISSUE THREAD

**Issue by brittonsmith** [yt-project/yt_astro_analysis#4]
Issue [#1290](https://github.com/yt-project/yt/issues/1290) from yt.
Originally reported by: Nathan Goldbaum (Bitbucket: ngoldbaum, GitHub: ngoldbaum)

Right now the halo catalog infrastructure does something fishy with field names in python 3. Specifically, take a look at input cell 16 in this notebook:

http://yt-project.org/docs/dev/cookbook/halo_analysis_example.html#Plotting-Radial-Profiles

Note how it uses stringified versions of field tuples. The field names are somehow getting converted to strings and this is making it into output files. This isn't what happens in python2.

**Comment by brittonsmith** [comment]
@ngoldbaum, I've just looked into this and the behavior does not seem to be limited to Python 3. The `write_profile` function in `halo_analysis/halo_callbacks.py` is sending `str(field)` as the dataset name to `h5py`. I think this was done (by me most likely) as a quick workaround for the fact that `h5py` does not allow tuples as dataset names.

I'd like to get your thoughts on how to proceed. I would say this is not so much a bug as just not the best way of doing things. I could fix this by naming the `h5py` dataset with just `fname` for a field named `(ftype, fname)` or I could try to make the load function a bit more clever and turn the stringified tuple back into an actual tuple. Either would technically be a backward compatibility break.  Additionally, this entire machinery could now be reduced to just a couple lines since `save_as_dataset` has since come along.

An additional option, which I think I may be in favor of, is to relabel this bug as an enhancement and request that this functionality simply be replaced with `save_as_dataset`-related code.  What do you think?

**Comment by ngoldbaum** [comment]
i’m fine with moving this functionality fully to `save_as_dataset`.

**Comment by brittonsmith** [comment]
Halo catalog saving was converted to use `save_as_dataset` in the big refactor. This is no longer an issue.
