### ISSUE TITLE
yt.extern.six references should be removed in the yt-4.0 branch

### ISSUE THREAD

**Issue by qobilidop** [yt-project/yt_astro_analysis#48]
[Vendored `six` is removed in yt's `yt-4.0` branch](https://github.com/yt-project/yt/commit/624cc27687df8049c06f5479b615d3574adc30ca), so all remaining `six` references here in the `yt-4.0` branch should be removed too, otherwise there could be import errors.

**Comment by jzuhone** [comment]
I'm working on this currently, hopefully will have a PR in the next day or so.

**Comment by matthewturk** [comment]
Whoa, I thought I snagged them all!  My apologies, and thanks for fixing this up.

**Comment by brittonsmith** [comment]
Resolved in PR #56.
